---
abstract: 'libraries historically supplied with Perl 4'
author:
  - 'Brandon S. Allbery'
  - 'John Bazik'
  - 'Tom Christiansen <tchrist@convex.com>'
  - 'Charles Collins'
  - 'Joe Doupnik <JRD@CC.USU.EDU>'
  - 'Marion Hakanson <hakanson@cse.ogi.edu>'
  - 'Waldemar Kebsch <kebsch.pad@nixpbe.UUCP>'
  - 'Lee McLoughlin <lmjm@doc.ic.ac.uk>'
  - '<A.Macpherson@bnr.co.uk>'
  - 'Randal L. Schwartz <merlyn@stonehenge.com>'
  - 'Aaron Sherman <asherman@fmrco.com>'
  - 'Wayne Thompson'
  - 'Larry Wall <lwall@jpl-devvax.jpl.nasa.gov>'
  - 'Ilya Zakharevich'
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl4-CoreLibs
provides:
  Perl4::CoreLibs:
    file: lib/Perl4/CoreLibs.pm
    version: 0.000
requires:
  File::Find: 0
  Getopt::Long: 0
  IPC::Open2: 0
  IPC::Open3: 0
  Socket: 0
  Text::ParseWords: 0
  Time::Local: 0
  perl: 5.006
  strict: 0
  warnings: 0
  warnings::register: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.000
